# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import bitket.models


class Migration(migrations.Migration):

    dependencies = [
        ('bitket', '0004_auto_20161212_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ('index', 'name'), 'verbose_name': 'ticket type', 'verbose_name_plural': 'ticket types'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('index', 'name'), 'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.AlterModelOptions(
            name='variationchoice',
            options={'ordering': ('index',), 'verbose_name': 'variation choice', 'verbose_name_plural': 'variation choices'},
        ),
        migrations.RemoveField(
            model_name='ticketownership',
            name='switch_code',
        ),
        migrations.AddField(
            model_name='ticketownership',
            name='code',
            field=models.CharField(default=bitket.models.generate_ticket_ownership_code, max_length=16, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='ticketownership',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='ticket_ownerships', to='bitket.Modifier', verbose_name='utilized modifiers'),
        ),
        migrations.AlterField(
            model_name='ticketownership',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='ticket_ownerships', to='bitket.Transaction', verbose_name='transactions'),
        ),
    ]
