image: docker:latest
services:
  - docker:dind
build-backend:
  stage: build
  script:
    - export BACKEND_IMAGE_TAG=backend-$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$BACKEND_IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$BACKEND_IMAGE_TAG"

build-frontend:
  stage: build
  script:
    - export FRONTEND_IMAGE_TAG=frontend-$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$FRONTEND_IMAGE_TAG" tickle-frontend
    - docker push "$CI_REGISTRY_IMAGE:$FRONTEND_IMAGE_TAG"
