image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - export COMMIT_TAG=$CI_COMMIT_SHA
    - export REF_TAG=$CI_COMMIT_REF_SLUG
    - docker build --pull -t $CI_REGISTRY_IMAGE:$COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$COMMIT_TAG $CI_REGISTRY_IMAGE:$REF_TAG
    - docker push $CI_REGISTRY_IMAGE:$COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$REF_TAG
