tests:
  image: quay.io/ovidner/tickle
  links:
    - postgres
    - redis
  command: /app/run/tests
  environment:
    CELERY_BROKER_URL: 'redis://redis.docker:6379/1'
    DJANGO_DATABASE_URL: 'postgres://tickle:tickle@postgres:5432/tickle'
    DJANGO_DEBUG: 'false'
    DJANGO_REDIS_URL: 'redis://redis.docker:6379/0'
    DJANGO_SECRET_KEY: 'ci'
    SAML_SP_ACS_URL: ''
    SAML_SP_KEY: '-----BEGIN RSA PRIVATE KEY----- -----END RSA PRIVATE KEY-----'
    SAML_SP_CERT: '-----BEGIN CERTIFICATE----- -----END CERTIFICATE-----'

postgres:
  image: postgres:9
  environment:
    POSTGRES_USER: 'tickle'
    POSTGRES_PASSWORD: 'tickle'

redis:
  image: redis:3
