postgres:
  image: postgres:9.5
  volumes:
    - /data/tickle/postgres:/var/lib/postgresql/data
  env_file: .env
  ports:
    - "127.0.0.1:5432:5432"

django:
  build: .
  links:
    - postgres
    - redis
  env_file: .env

redis:
  image: redis:3.0
  ports:
    - "127.0.0.1:6379:6379"
