# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='person',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='total_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liu_id',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_personal_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Blank means no limit.', null=True, verbose_name='maximum personal quantity'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_total_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Blank means no limit.', null=True, verbose_name='maximum total quantity'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
