# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickle', '0002_auto_20161208_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ('index', 'name'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['index', 'name'], 'verbose_name': 'product variation', 'verbose_name_plural': 'product variations'},
        ),
        migrations.AlterModelOptions(
            name='variationchoice',
            options={'ordering': ('index',), 'verbose_name': 'product variation choice', 'verbose_name_plural': 'product variation choices'},
        ),
    ]
