# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import tickle.common.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tickle.common.db.fields.NameField(max_length=64, verbose_name='name')),
                ('slug', tickle.common.db.fields.SlugField(editable=True, max_length=64, populate_from='name', unique_with=('organizer__slug',), verbose_name='slug')),
                ('description', tickle.common.db.fields.DescriptionField(blank=True, verbose_name='description')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
