# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160422_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_events', to='organizers.Organizer', verbose_name='organizer'),
        ),
    ]
