# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import tickle.common.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_authorized', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Stripe authorization timestamp')),
                ('stripe_live_mode', models.BooleanField(default=False, editable=False, verbose_name='Stripe live mode')),
                ('stripe_account_id', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Stripe account ID')),
                ('stripe_refresh_token', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Stripe refresh token')),
                ('stripe_public_key', models.CharField(blank=True, max_length=64, verbose_name='Stripe public key')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=64, verbose_name='Stripe secret key')),
                ('stripe_read_only', models.BooleanField(default=True, verbose_name='Stripe read only access')),
                ('name', tickle.common.db.fields.NameField(max_length=64, unique=True, verbose_name='name')),
                ('slug', tickle.common.db.fields.SlugField(editable=False, max_length=64, populate_from='name', unique=True, verbose_name='slug')),
            ],
        ),
    ]
