# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='admins',
            field=models.ManyToManyField(related_name='admin_for_organizers', to=settings.AUTH_USER_MODEL, verbose_name='admins'),
        ),
    ]
