# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='amount')),
                ('stripe_charge', models.CharField(max_length=64, verbose_name='Stripe charge')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
