# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variation',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variationchoice',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
