# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickle', '0003_auto_20161208_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_number',
            field=models.CharField(default='', max_length=12, verbose_name='organization number'),
            preserve_default=False,
        ),
    ]
