# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modifiers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodifier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modifiers', to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='holdingmodifier',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_modifiers', to='products.Holding', verbose_name='holding'),
        ),
        migrations.AddField(
            model_name='holdingmodifier',
            name='product_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_modifiers', to='modifiers.ProductModifier', verbose_name='product modifier'),
        ),
        migrations.AlterUniqueTogether(
            name='productmodifier',
            unique_together=set([('condition', 'product')]),
        ),
        migrations.AlterUniqueTogether(
            name='holdingmodifier',
            unique_together=set([('product_modifier', 'holding')]),
        ),
    ]
