# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Determines whether the condition should be displayed and included in queries.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='StudentUnionMemberCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conditions.Condition')),
            ],
            options={
                'verbose_name': 'student union member condition',
                'verbose_name_plural': 'student union member conditions',
            },
            bases=('conditions.condition',),
        ),
    ]
